### ISSUE TITLE
AnonPerth/AnonPerth-02 - preview not working

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#111]

**Comment by marcolarosa** [comment]
The following XML snippet - from the item `AnonPerth` page `AnonPerth-02`

```
<surface xmlns="http://www.tei-c.org/ns/1.0" xml:id="AnonPerth-02">
  <line>NATIVE <unclear>VOCABULARY.</unclear></line>
  <line>PERTH DISTRICT. <unclear>(contd.)</unclear></line>
  <table>
    <row>
      <cell>Keloo</cell>
      <cell>Mary Pool. (Compare with Keelo, Counties <unclear>Bernarba</unclear> & Finch, N.S.W.)</cell>
    </row>
  </table>
</surface>
```

Causes the following error when trying to load the preview:

```
nyingarn-workspace-api-1             | Error:
nyingarn-workspace-api-1             |     at L.<anonymous> (/srv/api/node_modules/core-js/internals/wrap-error-constructor-with-cause.js:37:62)
nyingarn-workspace-api-1             |     at L.Error (/srv/api/node_modules/core-js/modules/es.error.cause.js:28:43)
nyingarn-workspace-api-1             |     at new L (/srv/api/node_modules/saxon-js/SaxonJS2N.js:4109:549)
nyingarn-workspace-api-1             |     at Object.parseXmlFromString (/srv/api/node_modules/saxon-js/SaxonJS2N.js:4711:281)
nyingarn-workspace-api-1             |     at E (/srv/api/node_modules/saxon-js/SaxonJS2N.js:5014:122)
nyingarn-workspace-api-1             |     at Object.transform (/srv/api/node_modules/saxon-js/SaxonJS2N.js:5014:258)
nyingarn-workspace-api-1             |     at _callee$ (/srv/api/src/lib/transform.js:8:36)
nyingarn-workspace-api-1             |     at tryCatch (/srv/api/src/lib/transform.js:2:1)
nyingarn-workspace-api-1             |     at Generator._invoke (/srv/api/src/lib/transform.js:2:1)
nyingarn-workspace-api-1             |     at Generator.next (/srv/api/src/lib/transform.js:2:1)
nyingarn-workspace-api-1             |     at asyncGeneratorStep (/srv/api/src/lib/transform.js:2:1)
nyingarn-workspace-api-1             |     at _next (/srv/api/src/lib/transform.js:2:1)
nyingarn-workspace-api-1             |     at /srv/api/src/lib/transform.js:2:1
nyingarn-workspace-api-1             |     at new Promise (<anonymous>)
nyingarn-workspace-api-1             |     at /srv/api/src/lib/transform.js:2:1
nyingarn-workspace-api-1             |     at transformDocument (/srv/api/src/lib/transform.js:6:40)
nyingarn-workspace-api-1             |     at _callee21$ (/srv/api/src/routes/item.js:429:39)
nyingarn-workspace-api-1             |     at tryCatch (/srv/api/src/routes/item.js:2:1)
nyingarn-workspace-api-1             |     at Generator._invoke (/srv/api/src/routes/item.js:2:1)
nyingarn-workspace-api-1             |     at Generator.next (/srv/api/src/routes/item.js:2:1)
nyingarn-workspace-api-1             |     at asyncGeneratorStep (/srv/api/src/routes/item.js:2:1)
nyingarn-workspace-api-1             |     at _next (/srv/api/src/routes/item.js:2:1)
nyingarn-workspace-api-1             |     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
nyingarn-workspace-api-1             |   message: 'Invalid character in entity name at line 6 column 83',
nyingarn-workspace-api-1             |   name: 'XError',
nyingarn-workspace-api-1             |   code: 'FODC0002'
nyingarn-workspace-api-1             | }

```


Specifically removing the line:

```
 <cell>Mary Pool. (Compare with Keelo, Counties <unclear>Bernarba</unclear> & Finch, N.S.W.)</cell>
```

The issue seems to be with the `&`. Does that need to be encoded? Surely not....?

**Comment by nthieberger** [comment]
Yes, & needs to be escaped in xml. It needs to be &amp;

**Comment by marcolarosa** [comment]
Aaarrrrggghhhhh

**Comment by marcolarosa** [comment]
Question: Can we leave it as a normal '&' in the text and get the preview stylesheet to `fix` it as part of generating the preview. That way the workspace user see's:

```
Mary Pool ... & Finch ...)
```

Which aligns with what is in the image.

Rather than:
```
Mary Pool ... &amp; Finch ...)
```

**Comment by marcolarosa** [comment]
actually - nevermind. I'll answer my own question. No it can't.
