### ISSUE TITLE
Tiff processing failures need to clean up the tiff file

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#21]
If a tiff image is uploaded but it can't be handled by the processing code we need to remove it so that an upload of a jpeg will result in it being used as the source for the processing stages.

Error in console:

```
yesterday at 4:53:22 PM2022-02-21T05:53:22.356Z DEBUG: Creating '/tmp/66b5a471-8a93-4e05-882c-f8fa6123265f/BM1684A910/BM1684A910-0008.thumbnail_h300.jpg' from '/tmp/66b5a471-8a93-4e05-882c-f8fa6123265f/BM1684A910/BM1684A910-0008.tif'
yesterday at 4:53:22 PM2022-02-21T05:53:22.379Z ERROR: runTask ERROR: Task in /tmp/66b5a471-8a93-4e05-882c-f8fa6123265f
yesterday at 4:53:22 PMError: source input: Old-style JPEG compression support is not configured
yesterday at 4:53:22 PMsource input: Old-style JPEG compression support is not configured
yesterday at 4:53:22 PMsource input: Old-style JPEG compression support is not configured
yesterday at 4:53:22 PMsource input: Old-style JPEG compression support is not configured
yesterday at 4:53:22 PMsource input: Old-style JPEG compression support is not configured
yesterday at 4:53:22 PMsource input: Old-style JPEG compression support is not configured
yesterday at 4:53:22 PMsource input: Old-style JPEG compression support is not configured
yesterday at 4:53:22 PMsource input: Old-style JPEG compression support is not configured
yesterday at 4:53:22 PMsource input: Old-style JPEG compression support is not configured
yesterday at 4:53:22 PMsource input: Old-style JPEG compression support is not configured
yesterday at 4:53:22 PMtiff2vips: read error
yesterday at 4:53:22 PM
yesterday at 4:53:22 PM    at /srv/server.bundle.js:1:25249
yesterday at 4:53:22 PM    at tryCatch (/srv/node_modules/regenerator-runtime/runtime.js:63:40)
yesterday at 4:53:22 PM    at Generator.invoke [as _invoke] (/srv/node_modules/regenerator-runtime/runtime.js:294:22)
yesterday at 4:53:22 PM    at Generator.next (/srv/node_modules/regenerator-runtime/runtime.js:119:21)
yesterday at 4:53:22 PM    at f (/srv/server.bundle.js:1:23986)
yesterday at 4:53:22 PM    at o (/srv/server.bundle.js:1:24189)
```

**Comment by marcolarosa** [comment]
@sophlew after some investigation this looks to be really hard to do deterministically. However, not that a user can delete an individual file from a resource they can delete the broken tif and then upload a jpg to try again. For now, i'll leave this ticket open but i'll unmark it high priority. See how you go with the workaround.

**Comment by marcolarosa** [comment]
@sophlew For now we'll treat this as something we can document for users to follow. ie upload tiff and nothing happens then delete resource and start again with a jpeg.

**Comment by sophlew** [comment]
Information re this issue added to Nyingarn website

**Comment by sophlew** [comment]
this ticket can be closed
